#!/bin/bash

while read local_ref local_sha1 remote_ref remote_sha1
do
  for branch in "master" "production" "release"; do
    if [[ "${remote_ref##refs/heads/}" = "${branch}" ]]; then
    echo "Warning: You are pushing to the remote important branch, are you sure? [y/N]"

      exec < /dev/tty
      read ANSWER

      case $ANSWER in
        "Y" | "y" | "yes" | "Yes" | "YES" ) echo "OK. push start.";;
        * ) echo "push failed.";exit 1;;
      esac
      exit 0
    fi
  done
done
